name: asd_care_app
description: "ASD Care App"
publish_to: 'none' 

version: 1.0.5+2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter  # ✅ 加上這行    
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.4.4  # 添加 WebView 支援  
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.1.14
  yaml: ^3.1.2
  google_mobile_ads: ^5.3.1  # 請確保使用最新版本
  http: ^1.3.0  # ✅ 加入 http 套件
  package_info_plus: ^8.3.0  # ✅ 確保使用最新版本
  confetti: ^0.8.0
  shared_preferences: ^2.2.2
  easy_localization: ^3.0.0
  easy_localization_loader: ^2.0.2
  connectivity_plus: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/asd_care_logo.png
    - assets/menu_banner.png
    - assets/warm_welcome.png
    - assets/about_us_banner.png
    - assets/family_support.png
    - assets/sunrise_family.png
    - assets/asd_care_wallpaper.png
    - assets/asd_care_wallpaper_02.png
    - assets/asd_care_wallpaper_03.png
    - assets/asd_care_wallpaper_04.png
    - assets/memory_game_wallpaper.png    
    - assets/self_test_wallpaper.png
    - assets/source_wallpaper.png
    - assets/question_icon.png
    - assets/answer_icon.png
    - assets/doctor_icon.png    
    - assets/info_icon.png
    - assets/faqs/
    - assets/supports/
    - assets/translations/   
    - assets/questions/

easy_localization:
  assetLoader: YamlAssetLoader

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png" # 設定 APP ICON 的來源
  adaptive_icon_background: "#ffffff" # Android 自適應 ICON 背景（可用 HEX 色碼或圖片）
  adaptive_icon_foreground: "assets/app_icon.png" # Android 前景 ICON