name: asd_care_app
description: "ASD Care App"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.4.4  # 添加 WebView 支援  
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.1.14
  yaml: ^3.1.2
  google_mobile_ads: ^4.0.0  # 請確保使用最新版本
  http: ^0.13.6  # ✅ 加入 http 套件

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/asd_care_logo.png
    - assets/menu_banner.png
    - assets/warm_welcome.png
    - assets/about_us_banner.png
    - assets/family_support.png
    - assets/sunrise_family.png
    - assets/asd_care_wallpaper.png
    - assets/asd_care_wallpaper_02.png
    - assets/asd_care_wallpaper_03.png
    - assets/faqs.yaml
    - assets/question_icon.png
    - assets/answer_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png" # 設定 APP ICON 的來源
  adaptive_icon_background: "#ffffff" # Android 自適應 ICON 背景（可用 HEX 色碼或圖片）
  adaptive_icon_foreground: "assets/app_icon.png" # Android 前景 ICON